#------------------------------------------------------------------------------
# PlusCoder Configuration
#------------------------------------------------------------------------------

#------------------------------------------------------------------------------
# Application Behavior
#------------------------------------------------------------------------------
# streaming: true                 # Enable/disable LLM streaming
# user_feedback: true             # Enable/disable user feedback
# display_internal_outputs: false # Display internal agent outputs
# auto_confirm: false             # Auto-confirm pluscoder execution
# init: true                      # Enable/disable initial setup
initialized: true                      # Enable/disable initial setup
# read_only: false                # Enable/disable read-only mode
# user_input: ""                  # Predefined user input

#------------------------------------------------------------------------------
# File Paths
#------------------------------------------------------------------------------
# overview_filename: PROJECT_OVERVIEW.md     # Project overview filename
# log_filename: pluscoder.log                # Log filename
# overview_file_path: PROJECT_OVERVIEW.md    # Path to project overview file
# guidelines_file_path: CODING_GUIDELINES.md # Path to coding guidelines file

#------------------------------------------------------------------------------
# Model and API Settings
#------------------------------------------------------------------------------
model: openai/claude-3-5-sonnet-20240620 # LLM model to use
# model: anthropic.claude-3-5-sonnet-20240620-v1:0 # LLM model to use
provider: openai           # Provider (aws_bedrock, openai, litellm, anthropic)
# openai_api_key:          # OpenAI API key
# openai_api_base:         # OpenAI API base URL

#------------------------------------------------------------------------------
# AWS Settings
#------------------------------------------------------------------------------
# aws_access_key_id:       # AWS Access Key ID
# aws_secret_access_key:   # AWS Secret Access Key
# aws_profile: default     # AWS profile name

#------------------------------------------------------------------------------
# Git Settings
#------------------------------------------------------------------------------
auto_commits: true       # Enable/disable automatic Git commits
allow_dirty_commits: true # Allow commits in a dirty repository

#------------------------------------------------------------------------------
# Test and Lint Settings
#------------------------------------------------------------------------------
run_tests_after_edit: true  # Run tests after file edits
run_lint_after_edit: true   # Run linter after file edits
test_command: make test                # Command to run tests
lint_command: make lint                # Command to run linter
auto_run_linter_fix: true   # Auto-run linter fix before linting
lint_fix_command: make format        # Command to run linter fix

#------------------------------------------------------------------------------
# Repomap Settings
#------------------------------------------------------------------------------
# use_repomap: false           # Enable/disable repomap feature
# repomap_level: 2             # Repomap detail level (0: minimal, 1: moderate, 2: detailed)
# repomap_exclude_files: []    # List of files to exclude from repomap
repo_exclude_files: [".*.(png|jpg|jpeg|svg)"]       # Regex patterns to exclude files from repo operations

#------------------------------------------------------------------------------
# Display Options
#------------------------------------------------------------------------------
# show_repo: false             # Show repository information
# show_repomap: false          # Show repository map
# show_config: false           # Show configuration information

#------------------------------------------------------------------------------
# Custom Prompt Commands
#------------------------------------------------------------------------------
# Customs instructions to agents when using /custom <prompt_name> <additional instruction>
# Example: /custom hello then ask what are their needs
# custom_prompt_commands:
#   - prompt_name: hello
#     description: Greet the user says hello
#     prompt: Say hello to user
custom_agents:
  - name: CodeReviewer
    description: "Review code changes and provide feedback on code quality, best practices, and potential issues"
    prompt: "You are a code reviewer. Your task is to review code changes and provide feedback on code quality, best practices, and potential issues."
    
  - name: DocumentationWriter
    description: "Create and update project documentation, including README files, API documentation, and user guides"
    prompt: "You are a technical writer specializing in software documentation. Your task is to create and update project documentation, including README files, API documentation, and user guides."
    read_only: false
    
  - name: SecurityAuditor
    description: "Review code and configurations for potential security vulnerabilities and suggest security improvements"
    prompt: "You are a security expert. Your task is to review code and configurations for potential security vulnerabilities and suggest improvements to enhance the overall security of the project."
    read_only: true
