repos:
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: make test
        language: system
        pass_filenames: false
        always_run: true
      - id: ruff_check
        name: ruff_check
        entry: make check
        language: system
        pass_filenames: false
        always_run: true