repos:
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
      - id: ruff
        name: ruff
        entry: ruff check .
        language: system
        pass_filenames: false
        always_run: true
      - id: ruff-fix
        name: ruff (fix)
        entry: ruff check --fix .
        language: system
        pass_filenames: false
        always_run: true