
site_name: PlusCoder
site_description: Documentation for PlusCoder; Fully programmable agents with coding capabilities
site_author: granade.io
site_url: https://pluscoder.cl/docs

theme:
  name: material
  logo: "assets/pc.svg"
  favicon: "assets/pc.ico"
  font:
    text: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue', sans-serif
    code: source-code-pro, Menlo, Monaco, Consolas, 'Courier New', monospace
  features:
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - content.code.copy
    - content.code.annotate
    - search.suggest
    - search.highlight
    - color.scheme
    - instant.loading

  palette:
    # Default dark mode
    - scheme: slate
      primary: deep purple
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Light mode option
    - scheme: default
      primary: deep purple
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Automatic mode based on system preference
    - media: "(prefers-color-scheme)"
      scheme: slate
      primary: deep purple
      accent: blue
      toggle:
        icon: material/brightness-auto
        name: Switch to system preference

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_root_full_path: true
            show_signature_annotations: true
            separate_signature: true
            line_length: 88


nav:
  - index.md
  - installation.md
  - quick_start.md
  - contributing.md
  - Documentation:
    - Configuration: documentation/configuration.md
    - Agents: documentation/agents.md
    - Automation: documentation/automation.md
    - CLI:
      - Overview: documentation/cli.md
      - Commands: documentation/cli-commands.md
      - Features: documentation/cli-features.md
    - Providers: documentation/providers.md
    - Repository Indexing: documentation/indexing.md
  - Examples:
    - Basic: examples/basic.md
    - Issues Management: examples/custom_agent.md
    - Pull Requests Management: examples/custom_agent.md
    - Running with Docker: examples/custom_agent.md
    - Advanced Agents: examples/custom_agent.md
    - Remote Configuration: examples/custom_agent.md
  # - Running locally:
  #   - local/index.md
  #   - CLI: local/cli.md
  #   - Configuration: local/configuration.md
  #   - Talk to PlusCoder: local/talk_to_pluscoder.md
  #   - Agents: local/agents.md
  #   - Tools: local/tools.md
  #   - Tips & Tricks: local/tips_and_tricks.md
  # - Running in the Cloud:
  #   - cloud/index.md
  #   - Non-Interactive Modes: cloud/non_interactive_mode.md
  #   - Workflow Integration: cloud/workflow_automation.md
  # - API Reference:
  #   - Agents: api/agents.md
  #   - Tools: api/tools.md
  #   - Configuration: api/config.md

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.mark
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tilde
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true

copyright: "© 2024 Pluscoder. All rights reserved"

extra:
  generator: false

extra_css:
  - stylesheets/extra.css